// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: vmc/v1/agent.proto

package vmcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObservedState int32

const (
	ObservedState_OBSERVED_STATE_UNSPECIFIED ObservedState = 0
	ObservedState_OBSERVED_STATE_RUNNING     ObservedState = 1
	ObservedState_OBSERVED_STATE_SHUTOFF     ObservedState = 2
	ObservedState_OBSERVED_STATE_ABSENT      ObservedState = 3
)

// Enum value maps for ObservedState.
var (
	ObservedState_name = map[int32]string{
		0: "OBSERVED_STATE_UNSPECIFIED",
		1: "OBSERVED_STATE_RUNNING",
		2: "OBSERVED_STATE_SHUTOFF",
		3: "OBSERVED_STATE_ABSENT",
	}
	ObservedState_value = map[string]int32{
		"OBSERVED_STATE_UNSPECIFIED": 0,
		"OBSERVED_STATE_RUNNING":     1,
		"OBSERVED_STATE_SHUTOFF":     2,
		"OBSERVED_STATE_ABSENT":      3,
	}
)

func (x ObservedState) Enum() *ObservedState {
	p := new(ObservedState)
	*p = x
	return p
}

func (x ObservedState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObservedState) Descriptor() protoreflect.EnumDescriptor {
	return file_vmc_v1_agent_proto_enumTypes[0].Descriptor()
}

func (ObservedState) Type() protoreflect.EnumType {
	return &file_vmc_v1_agent_proto_enumTypes[0]
}

func (x ObservedState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObservedState.Descriptor instead.
func (ObservedState) EnumDescriptor() ([]byte, []int) {
	return file_vmc_v1_agent_proto_rawDescGZIP(), []int{0}
}

type ActionFailedRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Session         *NodeSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	VmId            string                 `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	PlacementEpoch  int64                  `protobuf:"varint,3,opt,name=placement_epoch,json=placementEpoch,proto3" json:"placement_epoch,omitempty"`
	DesiredRevision int64                  `protobuf:"varint,4,opt,name=desired_revision,json=desiredRevision,proto3" json:"desired_revision,omitempty"`
	AttemptToken    string                 `protobuf:"bytes,5,opt,name=attempt_token,json=attemptToken,proto3" json:"attempt_token,omitempty"`
	Error           string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	ErrorClass      string                 `protobuf:"bytes,7,opt,name=error_class,json=errorClass,proto3" json:"error_class,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActionFailedRequest) Reset() {
	*x = ActionFailedRequest{}
	mi := &file_vmc_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionFailedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionFailedRequest) ProtoMessage() {}

func (x *ActionFailedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionFailedRequest.ProtoReflect.Descriptor instead.
func (*ActionFailedRequest) Descriptor() ([]byte, []int) {
	return file_vmc_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ActionFailedRequest) GetSession() *NodeSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *ActionFailedRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ActionFailedRequest) GetPlacementEpoch() int64 {
	if x != nil {
		return x.PlacementEpoch
	}
	return 0
}

func (x *ActionFailedRequest) GetDesiredRevision() int64 {
	if x != nil {
		return x.DesiredRevision
	}
	return 0
}

func (x *ActionFailedRequest) GetAttemptToken() string {
	if x != nil {
		return x.AttemptToken
	}
	return ""
}

func (x *ActionFailedRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ActionFailedRequest) GetErrorClass() string {
	if x != nil {
		return x.ErrorClass
	}
	return ""
}

type ActionFailedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionFailedResponse) Reset() {
	*x = ActionFailedResponse{}
	mi := &file_vmc_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionFailedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionFailedResponse) ProtoMessage() {}

func (x *ActionFailedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionFailedResponse.ProtoReflect.Descriptor instead.
func (*ActionFailedResponse) Descriptor() ([]byte, []int) {
	return file_vmc_v1_agent_proto_rawDescGZIP(), []int{1}
}

type NodeSession struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeName          string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	SessionId         string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionGeneration int64                  `protobuf:"varint,3,opt,name=session_generation,json=sessionGeneration,proto3" json:"session_generation,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeSession) Reset() {
	*x = NodeSession{}
	mi := &file_vmc_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSession) ProtoMessage() {}

func (x *NodeSession) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSession.ProtoReflect.Descriptor instead.
func (*NodeSession) Descriptor() ([]byte, []int) {
	return file_vmc_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *NodeSession) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodeSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *NodeSession) GetSessionGeneration() int64 {
	if x != nil {
		return x.SessionGeneration
	}
	return 0
}

type RegisterHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Cpus          int64                  `protobuf:"varint,2,opt,name=cpus,proto3" json:"cpus,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	DiskBytes     uint64                 `protobuf:"varint,4,opt,name=disk_bytes,json=diskBytes,proto3" json:"disk_bytes,omitempty"`
	Nodes         []*NodeQuota           `protobuf:"bytes,5,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Lease         *durationpb.Duration   `protobuf:"bytes,6,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterHostRequest) Reset() {
	*x = RegisterHostRequest{}
	mi := &file_vmc_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHostRequest) ProtoMessage() {}

func (x *RegisterHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHostRequest.ProtoReflect.Descriptor instead.
func (*RegisterHostRequest) Descriptor() ([]byte, []int) {
	return file_vmc_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterHostRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RegisterHostRequest) GetCpus() int64 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *RegisterHostRequest) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *RegisterHostRequest) GetDiskBytes() uint64 {
	if x != nil {
		return x.DiskBytes
	}
	return 0
}

func (x *RegisterHostRequest) GetNodes() []*NodeQuota {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *RegisterHostRequest) GetLease() *durationpb.Duration {
	if x != nil {
		return x.Lease
	}
	return nil
}

type NodeQuota struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cpus          int64                  `protobuf:"varint,2,opt,name=cpus,proto3" json:"cpus,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	DiskBytes     uint64                 `protobuf:"varint,4,opt,name=disk_bytes,json=diskBytes,proto3" json:"disk_bytes,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeQuota) Reset() {
	*x = NodeQuota{}
	mi := &file_vmc_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeQuota) ProtoMessage() {}

func (x *NodeQuota) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeQuota.ProtoReflect.Descriptor instead.
func (*NodeQuota) Descriptor() ([]byte, []int) {
	return file_vmc_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *NodeQuota) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeQuota) GetCpus() int64 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *NodeQuota) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *NodeQuota) GetDiskBytes() uint64 {
	if x != nil {
		return x.DiskBytes
	}
	return 0
}

func (x *NodeQuota) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type RegisterHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*NodeSession         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterHostResponse) Reset() {
	*x = RegisterHostResponse{}
	mi := &file_vmc_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHostResponse) ProtoMessage() {}

func (x *RegisterHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHostResponse.ProtoReflect.Descriptor instead.
func (*RegisterHostResponse) Descriptor() ([]byte, []int) {
	return file_vmc_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterHostResponse) GetSessions() []*NodeSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *NodeSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Lease         *durationpb.Duration   `protobuf:"bytes,2,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_vmc_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_vmc_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetSession() *NodeSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *HeartbeatRequest) GetLease() *durationpb.Duration {
	if x != nil {
		return x.Lease
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_vmc_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_vmc_v1_agent_proto_rawDescGZIP(), []int{7}
}

type PollIntentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*NodeSession         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollIntentsRequest) Reset() {
	*x = PollIntentsRequest{}
	mi := &file_vmc_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollIntentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollIntentsRequest) ProtoMessage() {}

func (x *PollIntentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollIntentsRequest.ProtoReflect.Descriptor instead.
func (*PollIntentsRequest) Descriptor() ([]byte, []int) {
	return file_vmc_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *PollIntentsRequest) GetSessions() []*NodeSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// PollIntentsResponse is an authoritative snapshot: `complete` is the
// explicit completeness marker — local GC decisions are legal only against
// complete snapshots (plan §6.4).
type PollIntentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotToken string                 `protobuf:"bytes,1,opt,name=snapshot_token,json=snapshotToken,proto3" json:"snapshot_token,omitempty"`
	Complete      bool                   `protobuf:"varint,2,opt,name=complete,proto3" json:"complete,omitempty"`
	Intents       []*Intent              `protobuf:"bytes,3,rep,name=intents,proto3" json:"intents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollIntentsResponse) Reset() {
	*x = PollIntentsResponse{}
	mi := &file_vmc_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollIntentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollIntentsResponse) ProtoMessage() {}

func (x *PollIntentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollIntentsResponse.ProtoReflect.Descriptor instead.
func (*PollIntentsResponse) Descriptor() ([]byte, []int) {
	return file_vmc_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *PollIntentsResponse) GetSnapshotToken() string {
	if x != nil {
		return x.SnapshotToken
	}
	return ""
}

func (x *PollIntentsResponse) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *PollIntentsResponse) GetIntents() []*Intent {
	if x != nil {
		return x.Intents
	}
	return nil
}

// Intent is the desired state of one VM for one placement epoch. The
// daemon never acts on a revision older than one it has seen, and never
// acts at all before its grant commits.
type Intent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VmId            string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	VmName          string                 `protobuf:"bytes,2,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	NodeName        string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	PlacementEpoch  int64                  `protobuf:"varint,4,opt,name=placement_epoch,json=placementEpoch,proto3" json:"placement_epoch,omitempty"`
	DesiredRevision int64                  `protobuf:"varint,5,opt,name=desired_revision,json=desiredRevision,proto3" json:"desired_revision,omitempty"`
	// Tombstone intent: drive teardown, then send TeardownReceipt.
	Deleted bool    `protobuf:"varint,6,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Spec    *VmSpec `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	// Server-controlled retry pacing: do not attempt before this many
	// milliseconds from now (durable action-retry state lives server-side).
	NotBeforeMs int64 `protobuf:"varint,8,opt,name=not_before_ms,json=notBeforeMs,proto3" json:"not_before_ms,omitempty"`
	// Attempt token for idempotent result acceptance.
	AttemptToken  string `protobuf:"bytes,9,opt,name=attempt_token,json=attemptToken,proto3" json:"attempt_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Intent) Reset() {
	*x = Intent{}
	mi := &file_vmc_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Intent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intent) ProtoMessage() {}

func (x *Intent) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intent.ProtoReflect.Descriptor instead.
func (*Intent) Descriptor() ([]byte, []int) {
	return file_vmc_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *Intent) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *Intent) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *Intent) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Intent) GetPlacementEpoch() int64 {
	if x != nil {
		return x.PlacementEpoch
	}
	return 0
}

func (x *Intent) GetDesiredRevision() int64 {
	if x != nil {
		return x.DesiredRevision
	}
	return 0
}

func (x *Intent) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Intent) GetSpec() *VmSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Intent) GetNotBeforeMs() int64 {
	if x != nil {
		return x.NotBeforeMs
	}
	return 0
}

func (x *Intent) GetAttemptToken() string {
	if x != nil {
		return x.AttemptToken
	}
	return ""
}

type RequestGrantRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Session        *NodeSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	VmId           string                 `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	PlacementEpoch int64                  `protobuf:"varint,3,opt,name=placement_epoch,json=placementEpoch,proto3" json:"placement_epoch,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestGrantRequest) Reset() {
	*x = RequestGrantRequest{}
	mi := &file_vmc_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGrantRequest) ProtoMessage() {}

func (x *RequestGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGrantRequest.ProtoReflect.Descriptor instead.
func (*RequestGrantRequest) Descriptor() ([]byte, []int) {
	return file_vmc_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *RequestGrantRequest) GetSession() *NodeSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *RequestGrantRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *RequestGrantRequest) GetPlacementEpoch() int64 {
	if x != nil {
		return x.PlacementEpoch
	}
	return 0
}

type RequestGrantResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Granted bool                   `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`
	// Denial reason (admission predicate that failed) when granted=false.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGrantResponse) Reset() {
	*x = RequestGrantResponse{}
	mi := &file_vmc_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGrantResponse) ProtoMessage() {}

func (x *RequestGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGrantResponse.ProtoReflect.Descriptor instead.
func (*RequestGrantResponse) Descriptor() ([]byte, []int) {
	return file_vmc_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *RequestGrantResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *RequestGrantResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ReportRequest carries ordered evidence: (session_generation, report_seq)
// compared lexicographically per VM — a restarted daemon's fresh session
// starts at seq 1 without being rejected behind the old session's high
// sequence, while delayed old-session reports ARE rejected.
type ReportRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Session        *NodeSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	VmId           string                 `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	PlacementEpoch int64                  `protobuf:"varint,3,opt,name=placement_epoch,json=placementEpoch,proto3" json:"placement_epoch,omitempty"`
	ReportSeq      int64                  `protobuf:"varint,4,opt,name=report_seq,json=reportSeq,proto3" json:"report_seq,omitempty"`
	// The desired revision this report is evidence FOR (never inferred).
	AppliedRevision int64         `protobuf:"varint,5,opt,name=applied_revision,json=appliedRevision,proto3" json:"applied_revision,omitempty"`
	State           ObservedState `protobuf:"varint,6,opt,name=state,proto3,enum=vmc.v1.ObservedState" json:"state,omitempty"`
	Detail          string        `protobuf:"bytes,7,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_vmc_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_vmc_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ReportRequest) GetSession() *NodeSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *ReportRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ReportRequest) GetPlacementEpoch() int64 {
	if x != nil {
		return x.PlacementEpoch
	}
	return 0
}

func (x *ReportRequest) GetReportSeq() int64 {
	if x != nil {
		return x.ReportSeq
	}
	return 0
}

func (x *ReportRequest) GetAppliedRevision() int64 {
	if x != nil {
		return x.AppliedRevision
	}
	return 0
}

func (x *ReportRequest) GetState() ObservedState {
	if x != nil {
		return x.State
	}
	return ObservedState_OBSERVED_STATE_UNSPECIFIED
}

func (x *ReportRequest) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_vmc_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_vmc_v1_agent_proto_rawDescGZIP(), []int{14}
}

type TeardownReceiptRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Session        *NodeSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	VmId           string                 `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	PlacementEpoch int64                  `protobuf:"varint,3,opt,name=placement_epoch,json=placementEpoch,proto3" json:"placement_epoch,omitempty"`
	AttemptToken   string                 `protobuf:"bytes,4,opt,name=attempt_token,json=attemptToken,proto3" json:"attempt_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TeardownReceiptRequest) Reset() {
	*x = TeardownReceiptRequest{}
	mi := &file_vmc_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeardownReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeardownReceiptRequest) ProtoMessage() {}

func (x *TeardownReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeardownReceiptRequest.ProtoReflect.Descriptor instead.
func (*TeardownReceiptRequest) Descriptor() ([]byte, []int) {
	return file_vmc_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *TeardownReceiptRequest) GetSession() *NodeSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *TeardownReceiptRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *TeardownReceiptRequest) GetPlacementEpoch() int64 {
	if x != nil {
		return x.PlacementEpoch
	}
	return 0
}

func (x *TeardownReceiptRequest) GetAttemptToken() string {
	if x != nil {
		return x.AttemptToken
	}
	return ""
}

type TeardownReceiptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeardownReceiptResponse) Reset() {
	*x = TeardownReceiptResponse{}
	mi := &file_vmc_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeardownReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeardownReceiptResponse) ProtoMessage() {}

func (x *TeardownReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeardownReceiptResponse.ProtoReflect.Descriptor instead.
func (*TeardownReceiptResponse) Descriptor() ([]byte, []int) {
	return file_vmc_v1_agent_proto_rawDescGZIP(), []int{16}
}

var File_vmc_v1_agent_proto protoreflect.FileDescriptor

const file_vmc_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x12vmc/v1/agent.proto\x12\x06vmc.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x0fvmc/v1/vm.proto\"\x89\x02\n" +
	"\x13ActionFailedRequest\x12-\n" +
	"\asession\x18\x01 \x01(\v2\x13.vmc.v1.NodeSessionR\asession\x12\x13\n" +
	"\x05vm_id\x18\x02 \x01(\tR\x04vmId\x12'\n" +
	"\x0fplacement_epoch\x18\x03 \x01(\x03R\x0eplacementEpoch\x12)\n" +
	"\x10desired_revision\x18\x04 \x01(\x03R\x0fdesiredRevision\x12#\n" +
	"\rattempt_token\x18\x05 \x01(\tR\fattemptToken\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1f\n" +
	"\verror_class\x18\a \x01(\tR\n" +
	"errorClass\"\x16\n" +
	"\x14ActionFailedResponse\"x\n" +
	"\vNodeSession\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12-\n" +
	"\x12session_generation\x18\x03 \x01(\x03R\x11sessionGeneration\"\xde\x01\n" +
	"\x13RegisterHostRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x12\n" +
	"\x04cpus\x18\x02 \x01(\x03R\x04cpus\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x04R\vmemoryBytes\x12\x1d\n" +
	"\n" +
	"disk_bytes\x18\x04 \x01(\x04R\tdiskBytes\x12'\n" +
	"\x05nodes\x18\x05 \x03(\v2\x11.vmc.v1.NodeQuotaR\x05nodes\x12/\n" +
	"\x05lease\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x05lease\"\xe7\x01\n" +
	"\tNodeQuota\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04cpus\x18\x02 \x01(\x03R\x04cpus\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x04R\vmemoryBytes\x12\x1d\n" +
	"\n" +
	"disk_bytes\x18\x04 \x01(\x04R\tdiskBytes\x125\n" +
	"\x06labels\x18\x05 \x03(\v2\x1d.vmc.v1.NodeQuota.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x14RegisterHostResponse\x12/\n" +
	"\bsessions\x18\x01 \x03(\v2\x13.vmc.v1.NodeSessionR\bsessions\"r\n" +
	"\x10HeartbeatRequest\x12-\n" +
	"\asession\x18\x01 \x01(\v2\x13.vmc.v1.NodeSessionR\asession\x12/\n" +
	"\x05lease\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x05lease\"\x13\n" +
	"\x11HeartbeatResponse\"E\n" +
	"\x12PollIntentsRequest\x12/\n" +
	"\bsessions\x18\x01 \x03(\v2\x13.vmc.v1.NodeSessionR\bsessions\"\x82\x01\n" +
	"\x13PollIntentsResponse\x12%\n" +
	"\x0esnapshot_token\x18\x01 \x01(\tR\rsnapshotToken\x12\x1a\n" +
	"\bcomplete\x18\x02 \x01(\bR\bcomplete\x12(\n" +
	"\aintents\x18\x03 \x03(\v2\x0e.vmc.v1.IntentR\aintents\"\xae\x02\n" +
	"\x06Intent\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x17\n" +
	"\avm_name\x18\x02 \x01(\tR\x06vmName\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x12'\n" +
	"\x0fplacement_epoch\x18\x04 \x01(\x03R\x0eplacementEpoch\x12)\n" +
	"\x10desired_revision\x18\x05 \x01(\x03R\x0fdesiredRevision\x12\x18\n" +
	"\adeleted\x18\x06 \x01(\bR\adeleted\x12\"\n" +
	"\x04spec\x18\a \x01(\v2\x0e.vmc.v1.VmSpecR\x04spec\x12\"\n" +
	"\rnot_before_ms\x18\b \x01(\x03R\vnotBeforeMs\x12#\n" +
	"\rattempt_token\x18\t \x01(\tR\fattemptToken\"\x82\x01\n" +
	"\x13RequestGrantRequest\x12-\n" +
	"\asession\x18\x01 \x01(\v2\x13.vmc.v1.NodeSessionR\asession\x12\x13\n" +
	"\x05vm_id\x18\x02 \x01(\tR\x04vmId\x12'\n" +
	"\x0fplacement_epoch\x18\x03 \x01(\x03R\x0eplacementEpoch\"H\n" +
	"\x14RequestGrantResponse\x12\x18\n" +
	"\agranted\x18\x01 \x01(\bR\agranted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x8b\x02\n" +
	"\rReportRequest\x12-\n" +
	"\asession\x18\x01 \x01(\v2\x13.vmc.v1.NodeSessionR\asession\x12\x13\n" +
	"\x05vm_id\x18\x02 \x01(\tR\x04vmId\x12'\n" +
	"\x0fplacement_epoch\x18\x03 \x01(\x03R\x0eplacementEpoch\x12\x1d\n" +
	"\n" +
	"report_seq\x18\x04 \x01(\x03R\treportSeq\x12)\n" +
	"\x10applied_revision\x18\x05 \x01(\x03R\x0fappliedRevision\x12+\n" +
	"\x05state\x18\x06 \x01(\x0e2\x15.vmc.v1.ObservedStateR\x05state\x12\x16\n" +
	"\x06detail\x18\a \x01(\tR\x06detail\"\x10\n" +
	"\x0eReportResponse\"\xaa\x01\n" +
	"\x16TeardownReceiptRequest\x12-\n" +
	"\asession\x18\x01 \x01(\v2\x13.vmc.v1.NodeSessionR\asession\x12\x13\n" +
	"\x05vm_id\x18\x02 \x01(\tR\x04vmId\x12'\n" +
	"\x0fplacement_epoch\x18\x03 \x01(\x03R\x0eplacementEpoch\x12#\n" +
	"\rattempt_token\x18\x04 \x01(\tR\fattemptToken\"\x19\n" +
	"\x17TeardownReceiptResponse*\x82\x01\n" +
	"\rObservedState\x12\x1e\n" +
	"\x1aOBSERVED_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16OBSERVED_STATE_RUNNING\x10\x01\x12\x1a\n" +
	"\x16OBSERVED_STATE_SHUTOFF\x10\x02\x12\x19\n" +
	"\x15OBSERVED_STATE_ABSENT\x10\x032\x86\x04\n" +
	"\fAgentService\x12I\n" +
	"\fRegisterHost\x12\x1b.vmc.v1.RegisterHostRequest\x1a\x1c.vmc.v1.RegisterHostResponse\x12@\n" +
	"\tHeartbeat\x12\x18.vmc.v1.HeartbeatRequest\x1a\x19.vmc.v1.HeartbeatResponse\x12F\n" +
	"\vPollIntents\x12\x1a.vmc.v1.PollIntentsRequest\x1a\x1b.vmc.v1.PollIntentsResponse\x12I\n" +
	"\fRequestGrant\x12\x1b.vmc.v1.RequestGrantRequest\x1a\x1c.vmc.v1.RequestGrantResponse\x127\n" +
	"\x06Report\x12\x15.vmc.v1.ReportRequest\x1a\x16.vmc.v1.ReportResponse\x12R\n" +
	"\x0fTeardownReceipt\x12\x1e.vmc.v1.TeardownReceiptRequest\x1a\x1f.vmc.v1.TeardownReceiptResponse\x12I\n" +
	"\fActionFailed\x12\x1b.vmc.v1.ActionFailedRequest\x1a\x1c.vmc.v1.ActionFailedResponseB\x8b\x01\n" +
	"\n" +
	"com.vmc.v1B\n" +
	"AgentProtoP\x01Z8github.com/sigtunnel/vm-control-plane/proto/vmc/v1;vmcv1\xa2\x02\x03VXX\xaa\x02\x06Vmc.V1\xca\x02\x06Vmc\\V1\xe2\x02\x12Vmc\\V1\\GPBMetadata\xea\x02\aVmc::V1b\x06proto3"

var (
	file_vmc_v1_agent_proto_rawDescOnce sync.Once
	file_vmc_v1_agent_proto_rawDescData []byte
)

func file_vmc_v1_agent_proto_rawDescGZIP() []byte {
	file_vmc_v1_agent_proto_rawDescOnce.Do(func() {
		file_vmc_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vmc_v1_agent_proto_rawDesc), len(file_vmc_v1_agent_proto_rawDesc)))
	})
	return file_vmc_v1_agent_proto_rawDescData
}

var file_vmc_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vmc_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_vmc_v1_agent_proto_goTypes = []any{
	(ObservedState)(0),              // 0: vmc.v1.ObservedState
	(*ActionFailedRequest)(nil),     // 1: vmc.v1.ActionFailedRequest
	(*ActionFailedResponse)(nil),    // 2: vmc.v1.ActionFailedResponse
	(*NodeSession)(nil),             // 3: vmc.v1.NodeSession
	(*RegisterHostRequest)(nil),     // 4: vmc.v1.RegisterHostRequest
	(*NodeQuota)(nil),               // 5: vmc.v1.NodeQuota
	(*RegisterHostResponse)(nil),    // 6: vmc.v1.RegisterHostResponse
	(*HeartbeatRequest)(nil),        // 7: vmc.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 8: vmc.v1.HeartbeatResponse
	(*PollIntentsRequest)(nil),      // 9: vmc.v1.PollIntentsRequest
	(*PollIntentsResponse)(nil),     // 10: vmc.v1.PollIntentsResponse
	(*Intent)(nil),                  // 11: vmc.v1.Intent
	(*RequestGrantRequest)(nil),     // 12: vmc.v1.RequestGrantRequest
	(*RequestGrantResponse)(nil),    // 13: vmc.v1.RequestGrantResponse
	(*ReportRequest)(nil),           // 14: vmc.v1.ReportRequest
	(*ReportResponse)(nil),          // 15: vmc.v1.ReportResponse
	(*TeardownReceiptRequest)(nil),  // 16: vmc.v1.TeardownReceiptRequest
	(*TeardownReceiptResponse)(nil), // 17: vmc.v1.TeardownReceiptResponse
	nil,                             // 18: vmc.v1.NodeQuota.LabelsEntry
	(*durationpb.Duration)(nil),     // 19: google.protobuf.Duration
	(*VmSpec)(nil),                  // 20: vmc.v1.VmSpec
}
var file_vmc_v1_agent_proto_depIdxs = []int32{
	3,  // 0: vmc.v1.ActionFailedRequest.session:type_name -> vmc.v1.NodeSession
	5,  // 1: vmc.v1.RegisterHostRequest.nodes:type_name -> vmc.v1.NodeQuota
	19, // 2: vmc.v1.RegisterHostRequest.lease:type_name -> google.protobuf.Duration
	18, // 3: vmc.v1.NodeQuota.labels:type_name -> vmc.v1.NodeQuota.LabelsEntry
	3,  // 4: vmc.v1.RegisterHostResponse.sessions:type_name -> vmc.v1.NodeSession
	3,  // 5: vmc.v1.HeartbeatRequest.session:type_name -> vmc.v1.NodeSession
	19, // 6: vmc.v1.HeartbeatRequest.lease:type_name -> google.protobuf.Duration
	3,  // 7: vmc.v1.PollIntentsRequest.sessions:type_name -> vmc.v1.NodeSession
	11, // 8: vmc.v1.PollIntentsResponse.intents:type_name -> vmc.v1.Intent
	20, // 9: vmc.v1.Intent.spec:type_name -> vmc.v1.VmSpec
	3,  // 10: vmc.v1.RequestGrantRequest.session:type_name -> vmc.v1.NodeSession
	3,  // 11: vmc.v1.ReportRequest.session:type_name -> vmc.v1.NodeSession
	0,  // 12: vmc.v1.ReportRequest.state:type_name -> vmc.v1.ObservedState
	3,  // 13: vmc.v1.TeardownReceiptRequest.session:type_name -> vmc.v1.NodeSession
	4,  // 14: vmc.v1.AgentService.RegisterHost:input_type -> vmc.v1.RegisterHostRequest
	7,  // 15: vmc.v1.AgentService.Heartbeat:input_type -> vmc.v1.HeartbeatRequest
	9,  // 16: vmc.v1.AgentService.PollIntents:input_type -> vmc.v1.PollIntentsRequest
	12, // 17: vmc.v1.AgentService.RequestGrant:input_type -> vmc.v1.RequestGrantRequest
	14, // 18: vmc.v1.AgentService.Report:input_type -> vmc.v1.ReportRequest
	16, // 19: vmc.v1.AgentService.TeardownReceipt:input_type -> vmc.v1.TeardownReceiptRequest
	1,  // 20: vmc.v1.AgentService.ActionFailed:input_type -> vmc.v1.ActionFailedRequest
	6,  // 21: vmc.v1.AgentService.RegisterHost:output_type -> vmc.v1.RegisterHostResponse
	8,  // 22: vmc.v1.AgentService.Heartbeat:output_type -> vmc.v1.HeartbeatResponse
	10, // 23: vmc.v1.AgentService.PollIntents:output_type -> vmc.v1.PollIntentsResponse
	13, // 24: vmc.v1.AgentService.RequestGrant:output_type -> vmc.v1.RequestGrantResponse
	15, // 25: vmc.v1.AgentService.Report:output_type -> vmc.v1.ReportResponse
	17, // 26: vmc.v1.AgentService.TeardownReceipt:output_type -> vmc.v1.TeardownReceiptResponse
	2,  // 27: vmc.v1.AgentService.ActionFailed:output_type -> vmc.v1.ActionFailedResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_vmc_v1_agent_proto_init() }
func file_vmc_v1_agent_proto_init() {
	if File_vmc_v1_agent_proto != nil {
		return
	}
	file_vmc_v1_vm_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vmc_v1_agent_proto_rawDesc), len(file_vmc_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vmc_v1_agent_proto_goTypes,
		DependencyIndexes: file_vmc_v1_agent_proto_depIdxs,
		EnumInfos:         file_vmc_v1_agent_proto_enumTypes,
		MessageInfos:      file_vmc_v1_agent_proto_msgTypes,
	}.Build()
	File_vmc_v1_agent_proto = out.File
	file_vmc_v1_agent_proto_goTypes = nil
	file_vmc_v1_agent_proto_depIdxs = nil
}
