// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: vmc/v1/agent.proto

package vmcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_RegisterHost_FullMethodName    = "/vmc.v1.AgentService/RegisterHost"
	AgentService_Heartbeat_FullMethodName       = "/vmc.v1.AgentService/Heartbeat"
	AgentService_PollIntents_FullMethodName     = "/vmc.v1.AgentService/PollIntents"
	AgentService_RequestGrant_FullMethodName    = "/vmc.v1.AgentService/RequestGrant"
	AgentService_Report_FullMethodName          = "/vmc.v1.AgentService/Report"
	AgentService_TeardownReceipt_FullMethodName = "/vmc.v1.AgentService/TeardownReceipt"
	AgentService_ActionFailed_FullMethodName    = "/vmc.v1.AgentService/ActionFailed"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService is the daemon-facing surface (served by the control plane;
// the daemon PULLS — the control plane never dials into hosts, ADR-0004).
//
// Safety order for a placement: PollIntents shows work; RequestGrant makes
// exposure durable; only a committed grant permits substrate actions;
// Report carries ordered evidence; TeardownReceipt is the separate message
// type allowed to prove old-epoch cleanup.
type AgentServiceClient interface {
	RegisterHost(ctx context.Context, in *RegisterHostRequest, opts ...grpc.CallOption) (*RegisterHostResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	PollIntents(ctx context.Context, in *PollIntentsRequest, opts ...grpc.CallOption) (*PollIntentsResponse, error)
	RequestGrant(ctx context.Context, in *RequestGrantRequest, opts ...grpc.CallOption) (*RequestGrantResponse, error)
	Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
	TeardownReceipt(ctx context.Context, in *TeardownReceiptRequest, opts ...grpc.CallOption) (*TeardownReceiptResponse, error)
	// ActionFailed records a failed substrate attempt so retry pacing stays
	// durable server-side (an agent restart cannot reset backoff — plan D5).
	ActionFailed(ctx context.Context, in *ActionFailedRequest, opts ...grpc.CallOption) (*ActionFailedResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) RegisterHost(ctx context.Context, in *RegisterHostRequest, opts ...grpc.CallOption) (*RegisterHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterHostResponse)
	err := c.cc.Invoke(ctx, AgentService_RegisterHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, AgentService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) PollIntents(ctx context.Context, in *PollIntentsRequest, opts ...grpc.CallOption) (*PollIntentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollIntentsResponse)
	err := c.cc.Invoke(ctx, AgentService_PollIntents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RequestGrant(ctx context.Context, in *RequestGrantRequest, opts ...grpc.CallOption) (*RequestGrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestGrantResponse)
	err := c.cc.Invoke(ctx, AgentService_RequestGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, AgentService_Report_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) TeardownReceipt(ctx context.Context, in *TeardownReceiptRequest, opts ...grpc.CallOption) (*TeardownReceiptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TeardownReceiptResponse)
	err := c.cc.Invoke(ctx, AgentService_TeardownReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ActionFailed(ctx context.Context, in *ActionFailedRequest, opts ...grpc.CallOption) (*ActionFailedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionFailedResponse)
	err := c.cc.Invoke(ctx, AgentService_ActionFailed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService is the daemon-facing surface (served by the control plane;
// the daemon PULLS — the control plane never dials into hosts, ADR-0004).
//
// Safety order for a placement: PollIntents shows work; RequestGrant makes
// exposure durable; only a committed grant permits substrate actions;
// Report carries ordered evidence; TeardownReceipt is the separate message
// type allowed to prove old-epoch cleanup.
type AgentServiceServer interface {
	RegisterHost(context.Context, *RegisterHostRequest) (*RegisterHostResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	PollIntents(context.Context, *PollIntentsRequest) (*PollIntentsResponse, error)
	RequestGrant(context.Context, *RequestGrantRequest) (*RequestGrantResponse, error)
	Report(context.Context, *ReportRequest) (*ReportResponse, error)
	TeardownReceipt(context.Context, *TeardownReceiptRequest) (*TeardownReceiptResponse, error)
	// ActionFailed records a failed substrate attempt so retry pacing stays
	// durable server-side (an agent restart cannot reset backoff — plan D5).
	ActionFailed(context.Context, *ActionFailedRequest) (*ActionFailedResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) RegisterHost(context.Context, *RegisterHostRequest) (*RegisterHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterHost not implemented")
}
func (UnimplementedAgentServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedAgentServiceServer) PollIntents(context.Context, *PollIntentsRequest) (*PollIntentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PollIntents not implemented")
}
func (UnimplementedAgentServiceServer) RequestGrant(context.Context, *RequestGrantRequest) (*RequestGrantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestGrant not implemented")
}
func (UnimplementedAgentServiceServer) Report(context.Context, *ReportRequest) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedAgentServiceServer) TeardownReceipt(context.Context, *TeardownReceiptRequest) (*TeardownReceiptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TeardownReceipt not implemented")
}
func (UnimplementedAgentServiceServer) ActionFailed(context.Context, *ActionFailedRequest) (*ActionFailedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActionFailed not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_RegisterHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RegisterHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RegisterHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RegisterHost(ctx, req.(*RegisterHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_PollIntents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollIntentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PollIntents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_PollIntents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PollIntents(ctx, req.(*PollIntentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RequestGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RequestGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RequestGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RequestGrant(ctx, req.(*RequestGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Report_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Report(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_TeardownReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeardownReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).TeardownReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_TeardownReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).TeardownReceipt(ctx, req.(*TeardownReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ActionFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionFailedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ActionFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ActionFailed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ActionFailed(ctx, req.(*ActionFailedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vmc.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterHost",
			Handler:    _AgentService_RegisterHost_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _AgentService_Heartbeat_Handler,
		},
		{
			MethodName: "PollIntents",
			Handler:    _AgentService_PollIntents_Handler,
		},
		{
			MethodName: "RequestGrant",
			Handler:    _AgentService_RequestGrant_Handler,
		},
		{
			MethodName: "Report",
			Handler:    _AgentService_Report_Handler,
		},
		{
			MethodName: "TeardownReceipt",
			Handler:    _AgentService_TeardownReceipt_Handler,
		},
		{
			MethodName: "ActionFailed",
			Handler:    _AgentService_ActionFailed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vmc/v1/agent.proto",
}
