// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: vmc/v1/operation.proto

package vmcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Verb int32

const (
	Verb_VERB_UNSPECIFIED          Verb = 0
	Verb_VERB_CREATE               Verb = 1
	Verb_VERB_UPDATE_POWER         Verb = 2
	Verb_VERB_DELETE               Verb = 3
	Verb_VERB_SNAPSHOT_CREATE      Verb = 4
	Verb_VERB_SNAPSHOT_RESTORE     Verb = 5
	Verb_VERB_ADMIN_RETRY_CLEANUP  Verb = 6
	Verb_VERB_ADMIN_CLEAR_RECOVERY Verb = 7
)

// Enum value maps for Verb.
var (
	Verb_name = map[int32]string{
		0: "VERB_UNSPECIFIED",
		1: "VERB_CREATE",
		2: "VERB_UPDATE_POWER",
		3: "VERB_DELETE",
		4: "VERB_SNAPSHOT_CREATE",
		5: "VERB_SNAPSHOT_RESTORE",
		6: "VERB_ADMIN_RETRY_CLEANUP",
		7: "VERB_ADMIN_CLEAR_RECOVERY",
	}
	Verb_value = map[string]int32{
		"VERB_UNSPECIFIED":          0,
		"VERB_CREATE":               1,
		"VERB_UPDATE_POWER":         2,
		"VERB_DELETE":               3,
		"VERB_SNAPSHOT_CREATE":      4,
		"VERB_SNAPSHOT_RESTORE":     5,
		"VERB_ADMIN_RETRY_CLEANUP":  6,
		"VERB_ADMIN_CLEAR_RECOVERY": 7,
	}
)

func (x Verb) Enum() *Verb {
	p := new(Verb)
	*p = x
	return p
}

func (x Verb) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verb) Descriptor() protoreflect.EnumDescriptor {
	return file_vmc_v1_operation_proto_enumTypes[0].Descriptor()
}

func (Verb) Type() protoreflect.EnumType {
	return &file_vmc_v1_operation_proto_enumTypes[0]
}

func (x Verb) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verb.Descriptor instead.
func (Verb) EnumDescriptor() ([]byte, []int) {
	return file_vmc_v1_operation_proto_rawDescGZIP(), []int{0}
}

type OperationState int32

const (
	OperationState_OPERATION_STATE_UNSPECIFIED       OperationState = 0
	OperationState_OPERATION_STATE_PENDING           OperationState = 1
	OperationState_OPERATION_STATE_RUNNING           OperationState = 2
	OperationState_OPERATION_STATE_DONE              OperationState = 3
	OperationState_OPERATION_STATE_FAILED            OperationState = 4
	OperationState_OPERATION_STATE_SUPERSEDED        OperationState = 5
	OperationState_OPERATION_STATE_DEADLINE_EXCEEDED OperationState = 6
)

// Enum value maps for OperationState.
var (
	OperationState_name = map[int32]string{
		0: "OPERATION_STATE_UNSPECIFIED",
		1: "OPERATION_STATE_PENDING",
		2: "OPERATION_STATE_RUNNING",
		3: "OPERATION_STATE_DONE",
		4: "OPERATION_STATE_FAILED",
		5: "OPERATION_STATE_SUPERSEDED",
		6: "OPERATION_STATE_DEADLINE_EXCEEDED",
	}
	OperationState_value = map[string]int32{
		"OPERATION_STATE_UNSPECIFIED":       0,
		"OPERATION_STATE_PENDING":           1,
		"OPERATION_STATE_RUNNING":           2,
		"OPERATION_STATE_DONE":              3,
		"OPERATION_STATE_FAILED":            4,
		"OPERATION_STATE_SUPERSEDED":        5,
		"OPERATION_STATE_DEADLINE_EXCEEDED": 6,
	}
)

func (x OperationState) Enum() *OperationState {
	p := new(OperationState)
	*p = x
	return p
}

func (x OperationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationState) Descriptor() protoreflect.EnumDescriptor {
	return file_vmc_v1_operation_proto_enumTypes[1].Descriptor()
}

func (OperationState) Type() protoreflect.EnumType {
	return &file_vmc_v1_operation_proto_enumTypes[1]
}

func (x OperationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationState.Descriptor instead.
func (OperationState) EnumDescriptor() ([]byte, []int) {
	return file_vmc_v1_operation_proto_rawDescGZIP(), []int{1}
}

// Operation is the long-running result of every mutating RPC. Operations
// ALWAYS terminate (plan D3): realized -> DONE; a newer revision realized
// first -> SUPERSEDED; retry budget exhausted -> FAILED (same transaction as
// the phase write); per-verb deadline expiry -> DEADLINE_EXCEEDED without
// unsafe cleanup. Delete operations remain queryable after their resource
// row is gone.
type Operation struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ResourceType string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId   string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceName string                 `protobuf:"bytes,4,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Verb         Verb                   `protobuf:"varint,5,opt,name=verb,proto3,enum=vmc.v1.Verb" json:"verb,omitempty"`
	// The desired revision this operation will realize. Completion requires
	// evidence of exactly this revision.
	TargetRevision int64          `protobuf:"varint,6,opt,name=target_revision,json=targetRevision,proto3" json:"target_revision,omitempty"`
	State          OperationState `protobuf:"varint,7,opt,name=state,proto3,enum=vmc.v1.OperationState" json:"state,omitempty"`
	// Terminal result detail; immutable once the state is terminal.
	Error string `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	// Database-clock deadline after which the operation terminalizes as
	// DEADLINE_EXCEEDED even if no retry budget was consumed.
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=deadline,proto3" json:"deadline,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	FinishTime    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=finish_time,json=finishTime,proto3" json:"finish_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_vmc_v1_operation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_operation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_vmc_v1_operation_proto_rawDescGZIP(), []int{0}
}

func (x *Operation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Operation) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *Operation) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *Operation) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *Operation) GetVerb() Verb {
	if x != nil {
		return x.Verb
	}
	return Verb_VERB_UNSPECIFIED
}

func (x *Operation) GetTargetRevision() int64 {
	if x != nil {
		return x.TargetRevision
	}
	return 0
}

func (x *Operation) GetState() OperationState {
	if x != nil {
		return x.State
	}
	return OperationState_OPERATION_STATE_UNSPECIFIED
}

func (x *Operation) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Operation) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *Operation) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Operation) GetFinishTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishTime
	}
	return nil
}

var File_vmc_v1_operation_proto protoreflect.FileDescriptor

const file_vmc_v1_operation_proto_rawDesc = "" +
	"\n" +
	"\x16vmc/v1/operation.proto\x12\x06vmc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc7\x03\n" +
	"\tOperation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rresource_name\x18\x04 \x01(\tR\fresourceName\x12 \n" +
	"\x04verb\x18\x05 \x01(\x0e2\f.vmc.v1.VerbR\x04verb\x12'\n" +
	"\x0ftarget_revision\x18\x06 \x01(\x03R\x0etargetRevision\x12,\n" +
	"\x05state\x18\a \x01(\x0e2\x16.vmc.v1.OperationStateR\x05state\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x126\n" +
	"\bdeadline\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12;\n" +
	"\vcreate_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vfinish_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishTime*\xc7\x01\n" +
	"\x04Verb\x12\x14\n" +
	"\x10VERB_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vVERB_CREATE\x10\x01\x12\x15\n" +
	"\x11VERB_UPDATE_POWER\x10\x02\x12\x0f\n" +
	"\vVERB_DELETE\x10\x03\x12\x18\n" +
	"\x14VERB_SNAPSHOT_CREATE\x10\x04\x12\x19\n" +
	"\x15VERB_SNAPSHOT_RESTORE\x10\x05\x12\x1c\n" +
	"\x18VERB_ADMIN_RETRY_CLEANUP\x10\x06\x12\x1d\n" +
	"\x19VERB_ADMIN_CLEAR_RECOVERY\x10\a*\xe8\x01\n" +
	"\x0eOperationState\x12\x1f\n" +
	"\x1bOPERATION_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17OPERATION_STATE_PENDING\x10\x01\x12\x1b\n" +
	"\x17OPERATION_STATE_RUNNING\x10\x02\x12\x18\n" +
	"\x14OPERATION_STATE_DONE\x10\x03\x12\x1a\n" +
	"\x16OPERATION_STATE_FAILED\x10\x04\x12\x1e\n" +
	"\x1aOPERATION_STATE_SUPERSEDED\x10\x05\x12%\n" +
	"!OPERATION_STATE_DEADLINE_EXCEEDED\x10\x06B\x8f\x01\n" +
	"\n" +
	"com.vmc.v1B\x0eOperationProtoP\x01Z8github.com/sigtunnel/vm-control-plane/proto/vmc/v1;vmcv1\xa2\x02\x03VXX\xaa\x02\x06Vmc.V1\xca\x02\x06Vmc\\V1\xe2\x02\x12Vmc\\V1\\GPBMetadata\xea\x02\aVmc::V1b\x06proto3"

var (
	file_vmc_v1_operation_proto_rawDescOnce sync.Once
	file_vmc_v1_operation_proto_rawDescData []byte
)

func file_vmc_v1_operation_proto_rawDescGZIP() []byte {
	file_vmc_v1_operation_proto_rawDescOnce.Do(func() {
		file_vmc_v1_operation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vmc_v1_operation_proto_rawDesc), len(file_vmc_v1_operation_proto_rawDesc)))
	})
	return file_vmc_v1_operation_proto_rawDescData
}

var file_vmc_v1_operation_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_vmc_v1_operation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vmc_v1_operation_proto_goTypes = []any{
	(Verb)(0),                     // 0: vmc.v1.Verb
	(OperationState)(0),           // 1: vmc.v1.OperationState
	(*Operation)(nil),             // 2: vmc.v1.Operation
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_vmc_v1_operation_proto_depIdxs = []int32{
	0, // 0: vmc.v1.Operation.verb:type_name -> vmc.v1.Verb
	1, // 1: vmc.v1.Operation.state:type_name -> vmc.v1.OperationState
	3, // 2: vmc.v1.Operation.deadline:type_name -> google.protobuf.Timestamp
	3, // 3: vmc.v1.Operation.create_time:type_name -> google.protobuf.Timestamp
	3, // 4: vmc.v1.Operation.finish_time:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_vmc_v1_operation_proto_init() }
func file_vmc_v1_operation_proto_init() {
	if File_vmc_v1_operation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vmc_v1_operation_proto_rawDesc), len(file_vmc_v1_operation_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vmc_v1_operation_proto_goTypes,
		DependencyIndexes: file_vmc_v1_operation_proto_depIdxs,
		EnumInfos:         file_vmc_v1_operation_proto_enumTypes,
		MessageInfos:      file_vmc_v1_operation_proto_msgTypes,
	}.Build()
	File_vmc_v1_operation_proto = out.File
	file_vmc_v1_operation_proto_goTypes = nil
	file_vmc_v1_operation_proto_depIdxs = nil
}
