// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: vmc/v1/operation_service.proto

package vmcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_vmc_v1_operation_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_operation_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_vmc_v1_operation_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetOperationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WaitOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitOperationRequest) Reset() {
	*x = WaitOperationRequest{}
	mi := &file_vmc_v1_operation_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitOperationRequest) ProtoMessage() {}

func (x *WaitOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_operation_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitOperationRequest.ProtoReflect.Descriptor instead.
func (*WaitOperationRequest) Descriptor() ([]byte, []int) {
	return file_vmc_v1_operation_service_proto_rawDescGZIP(), []int{1}
}

func (x *WaitOperationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WaitOperationRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

var File_vmc_v1_operation_service_proto protoreflect.FileDescriptor

const file_vmc_v1_operation_service_proto_rawDesc = "" +
	"\n" +
	"\x1evmc/v1/operation_service.proto\x12\x06vmc.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x16vmc/v1/operation.proto\"%\n" +
	"\x13GetOperationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"[\n" +
	"\x14WaitOperationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout2\x94\x01\n" +
	"\x10OperationService\x12>\n" +
	"\fGetOperation\x12\x1b.vmc.v1.GetOperationRequest\x1a\x11.vmc.v1.Operation\x12@\n" +
	"\rWaitOperation\x12\x1c.vmc.v1.WaitOperationRequest\x1a\x11.vmc.v1.OperationB\x96\x01\n" +
	"\n" +
	"com.vmc.v1B\x15OperationServiceProtoP\x01Z8github.com/sigtunnel/vm-control-plane/proto/vmc/v1;vmcv1\xa2\x02\x03VXX\xaa\x02\x06Vmc.V1\xca\x02\x06Vmc\\V1\xe2\x02\x12Vmc\\V1\\GPBMetadata\xea\x02\aVmc::V1b\x06proto3"

var (
	file_vmc_v1_operation_service_proto_rawDescOnce sync.Once
	file_vmc_v1_operation_service_proto_rawDescData []byte
)

func file_vmc_v1_operation_service_proto_rawDescGZIP() []byte {
	file_vmc_v1_operation_service_proto_rawDescOnce.Do(func() {
		file_vmc_v1_operation_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vmc_v1_operation_service_proto_rawDesc), len(file_vmc_v1_operation_service_proto_rawDesc)))
	})
	return file_vmc_v1_operation_service_proto_rawDescData
}

var file_vmc_v1_operation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vmc_v1_operation_service_proto_goTypes = []any{
	(*GetOperationRequest)(nil),  // 0: vmc.v1.GetOperationRequest
	(*WaitOperationRequest)(nil), // 1: vmc.v1.WaitOperationRequest
	(*durationpb.Duration)(nil),  // 2: google.protobuf.Duration
	(*Operation)(nil),            // 3: vmc.v1.Operation
}
var file_vmc_v1_operation_service_proto_depIdxs = []int32{
	2, // 0: vmc.v1.WaitOperationRequest.timeout:type_name -> google.protobuf.Duration
	0, // 1: vmc.v1.OperationService.GetOperation:input_type -> vmc.v1.GetOperationRequest
	1, // 2: vmc.v1.OperationService.WaitOperation:input_type -> vmc.v1.WaitOperationRequest
	3, // 3: vmc.v1.OperationService.GetOperation:output_type -> vmc.v1.Operation
	3, // 4: vmc.v1.OperationService.WaitOperation:output_type -> vmc.v1.Operation
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vmc_v1_operation_service_proto_init() }
func file_vmc_v1_operation_service_proto_init() {
	if File_vmc_v1_operation_service_proto != nil {
		return
	}
	file_vmc_v1_operation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vmc_v1_operation_service_proto_rawDesc), len(file_vmc_v1_operation_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vmc_v1_operation_service_proto_goTypes,
		DependencyIndexes: file_vmc_v1_operation_service_proto_depIdxs,
		MessageInfos:      file_vmc_v1_operation_service_proto_msgTypes,
	}.Build()
	File_vmc_v1_operation_service_proto = out.File
	file_vmc_v1_operation_service_proto_goTypes = nil
	file_vmc_v1_operation_service_proto_depIdxs = nil
}
