// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: vmc/v1/vm.proto

package vmcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PowerState int32

const (
	PowerState_POWER_STATE_UNSPECIFIED PowerState = 0
	PowerState_POWER_STATE_RUNNING     PowerState = 1
	PowerState_POWER_STATE_STOPPED     PowerState = 2
)

// Enum value maps for PowerState.
var (
	PowerState_name = map[int32]string{
		0: "POWER_STATE_UNSPECIFIED",
		1: "POWER_STATE_RUNNING",
		2: "POWER_STATE_STOPPED",
	}
	PowerState_value = map[string]int32{
		"POWER_STATE_UNSPECIFIED": 0,
		"POWER_STATE_RUNNING":     1,
		"POWER_STATE_STOPPED":     2,
	}
)

func (x PowerState) Enum() *PowerState {
	p := new(PowerState)
	*p = x
	return p
}

func (x PowerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PowerState) Descriptor() protoreflect.EnumDescriptor {
	return file_vmc_v1_vm_proto_enumTypes[0].Descriptor()
}

func (PowerState) Type() protoreflect.EnumType {
	return &file_vmc_v1_vm_proto_enumTypes[0]
}

func (x PowerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PowerState.Descriptor instead.
func (PowerState) EnumDescriptor() ([]byte, []int) {
	return file_vmc_v1_vm_proto_rawDescGZIP(), []int{0}
}

type Phase int32

const (
	Phase_PHASE_UNSPECIFIED  Phase = 0
	Phase_PHASE_PENDING      Phase = 1
	Phase_PHASE_SCHEDULING   Phase = 2
	Phase_PHASE_PROVISIONING Phase = 3
	Phase_PHASE_RUNNING      Phase = 4
	Phase_PHASE_STOPPED      Phase = 5
	// Node lost after the placement was exposed (execution grant committed):
	// never rescheduled automatically — two VMs is worse than one late VM.
	Phase_PHASE_UNKNOWN Phase = 6
	// Durable retry budget exhausted or permanent error; the matching
	// operation is terminalized in the same transaction.
	Phase_PHASE_FAILED   Phase = 7
	Phase_PHASE_DELETING Phase = 8
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PHASE_PENDING",
		2: "PHASE_SCHEDULING",
		3: "PHASE_PROVISIONING",
		4: "PHASE_RUNNING",
		5: "PHASE_STOPPED",
		6: "PHASE_UNKNOWN",
		7: "PHASE_FAILED",
		8: "PHASE_DELETING",
	}
	Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED":  0,
		"PHASE_PENDING":      1,
		"PHASE_SCHEDULING":   2,
		"PHASE_PROVISIONING": 3,
		"PHASE_RUNNING":      4,
		"PHASE_STOPPED":      5,
		"PHASE_UNKNOWN":      6,
		"PHASE_FAILED":       7,
		"PHASE_DELETING":     8,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_vmc_v1_vm_proto_enumTypes[1].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_vmc_v1_vm_proto_enumTypes[1]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_vmc_v1_vm_proto_rawDescGZIP(), []int{1}
}

// VirtualMachine is the core resource: a spec the user owns, a status the
// reconciler owns, and the revision vocabulary that fences every writer
// (implementation plan §6).
type VirtualMachine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ResourceMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Spec          *VmSpec                `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *VmStatus              `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMachine) Reset() {
	*x = VirtualMachine{}
	mi := &file_vmc_v1_vm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMachine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachine) ProtoMessage() {}

func (x *VirtualMachine) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_vm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachine.ProtoReflect.Descriptor instead.
func (*VirtualMachine) Descriptor() ([]byte, []int) {
	return file_vmc_v1_vm_proto_rawDescGZIP(), []int{0}
}

func (x *VirtualMachine) GetMeta() *ResourceMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *VirtualMachine) GetSpec() *VmSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *VirtualMachine) GetStatus() *VmStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// ResourceMeta is shared by all resources.
type ResourceMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned UUID, stable for the resource's lifetime.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Unique human name (DNS-label constrained).
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Bumped on every user-visible spec change. In v0.1 only the desired
	// power state is mutable.
	SpecGeneration int64 `protobuf:"varint,3,opt,name=spec_generation,json=specGeneration,proto3" json:"spec_generation,omitempty"`
	// Optimistic-lock version: bumped on EVERY row write by any writer.
	ResourceVersion int64 `protobuf:"varint,4,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	// Monotonic desired revision: spec generations plus the deletion
	// tombstone. Agents never act on an older revision than one they have
	// already seen for the VM.
	DesiredRevision int64                  `protobuf:"varint,5,opt,name=desired_revision,json=desiredRevision,proto3" json:"desired_revision,omitempty"`
	CreateTime      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// Set when the resource is tombstoned; the row outlives the substrate
	// resources it drives (deletion is reconciliation too).
	DeleteTime    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=delete_time,json=deleteTime,proto3" json:"delete_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceMeta) Reset() {
	*x = ResourceMeta{}
	mi := &file_vmc_v1_vm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceMeta) ProtoMessage() {}

func (x *ResourceMeta) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_vm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceMeta.ProtoReflect.Descriptor instead.
func (*ResourceMeta) Descriptor() ([]byte, []int) {
	return file_vmc_v1_vm_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceMeta) GetSpecGeneration() int64 {
	if x != nil {
		return x.SpecGeneration
	}
	return 0
}

func (x *ResourceMeta) GetResourceVersion() int64 {
	if x != nil {
		return x.ResourceVersion
	}
	return 0
}

func (x *ResourceMeta) GetDesiredRevision() int64 {
	if x != nil {
		return x.DesiredRevision
	}
	return 0
}

func (x *ResourceMeta) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *ResourceMeta) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *ResourceMeta) GetDeleteTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeleteTime
	}
	return nil
}

type VmSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of virtual CPUs. Immutable after create.
	Cpus uint32 `protobuf:"varint,1,opt,name=cpus,proto3" json:"cpus,omitempty"`
	// Guest memory in bytes. Immutable after create.
	MemoryBytes uint64 `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	// Backing image reference (e.g. "ubuntu-24.04"). Immutable after create.
	Image string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	// Root disk virtual size in bytes; must be >= the backing image's
	// virtual size. Immutable after create.
	RootDiskBytes uint64 `protobuf:"varint,4,opt,name=root_disk_bytes,json=rootDiskBytes,proto3" json:"root_disk_bytes,omitempty"`
	// Optional tenant network name; empty means management NIC only.
	// Immutable after create.
	Network string `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	// The only mutable field in v0.1 (vmctl start/stop).
	Power PowerState `protobuf:"varint,6,opt,name=power,proto3,enum=vmc.v1.PowerState" json:"power,omitempty"`
	// Scheduling constraints: every key=value must match node labels.
	Constraints   map[string]string `protobuf:"bytes,7,rep,name=constraints,proto3" json:"constraints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Labels        map[string]string `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmSpec) Reset() {
	*x = VmSpec{}
	mi := &file_vmc_v1_vm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmSpec) ProtoMessage() {}

func (x *VmSpec) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_vm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmSpec.ProtoReflect.Descriptor instead.
func (*VmSpec) Descriptor() ([]byte, []int) {
	return file_vmc_v1_vm_proto_rawDescGZIP(), []int{2}
}

func (x *VmSpec) GetCpus() uint32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *VmSpec) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *VmSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *VmSpec) GetRootDiskBytes() uint64 {
	if x != nil {
		return x.RootDiskBytes
	}
	return 0
}

func (x *VmSpec) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *VmSpec) GetPower() PowerState {
	if x != nil {
		return x.Power
	}
	return PowerState_POWER_STATE_UNSPECIFIED
}

func (x *VmSpec) GetConstraints() map[string]string {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *VmSpec) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type VmStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Phase Phase                  `protobuf:"varint,1,opt,name=phase,proto3,enum=vmc.v1.Phase" json:"phase,omitempty"`
	// Logical node this VM is placed on (empty until scheduled).
	Node string `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	// Fencing token: bumped on every (re)assignment. Stamped on every
	// substrate artifact this VM owns.
	PlacementEpoch int64 `protobuf:"varint,3,opt,name=placement_epoch,json=placementEpoch,proto3" json:"placement_epoch,omitempty"`
	// The desired revision the agent most recently realized, from
	// evidence-bearing reports — never inferred from the desired row.
	AppliedRevision int64 `protobuf:"varint,4,opt,name=applied_revision,json=appliedRevision,proto3" json:"applied_revision,omitempty"`
	// Management-NIC address discovered from the DHCP lease.
	MgmtIp string `protobuf:"bytes,5,opt,name=mgmt_ip,json=mgmtIp,proto3" json:"mgmt_ip,omitempty"`
	// Last terminal error (phase FAILED).
	LastError     string       `protobuf:"bytes,6,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Conditions    []*Condition `protobuf:"bytes,7,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmStatus) Reset() {
	*x = VmStatus{}
	mi := &file_vmc_v1_vm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmStatus) ProtoMessage() {}

func (x *VmStatus) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_vm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmStatus.ProtoReflect.Descriptor instead.
func (*VmStatus) Descriptor() ([]byte, []int) {
	return file_vmc_v1_vm_proto_rawDescGZIP(), []int{3}
}

func (x *VmStatus) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *VmStatus) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *VmStatus) GetPlacementEpoch() int64 {
	if x != nil {
		return x.PlacementEpoch
	}
	return 0
}

func (x *VmStatus) GetAppliedRevision() int64 {
	if x != nil {
		return x.AppliedRevision
	}
	return 0
}

func (x *VmStatus) GetMgmtIp() string {
	if x != nil {
		return x.MgmtIp
	}
	return ""
}

func (x *VmStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *VmStatus) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

// Condition surfaces non-phase state (Unschedulable, RestartRequired, …).
type Condition struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Active           bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Reason           string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message          string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ObservedRevision int64                  `protobuf:"varint,5,opt,name=observed_revision,json=observedRevision,proto3" json:"observed_revision,omitempty"`
	UpdateTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_vmc_v1_vm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_vm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_vmc_v1_vm_proto_rawDescGZIP(), []int{4}
}

func (x *Condition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Condition) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Condition) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Condition) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Condition) GetObservedRevision() int64 {
	if x != nil {
		return x.ObservedRevision
	}
	return 0
}

func (x *Condition) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

var File_vmc_v1_vm_proto protoreflect.FileDescriptor

const file_vmc_v1_vm_proto_rawDesc = "" +
	"\n" +
	"\x0fvmc/v1/vm.proto\x12\x06vmc.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x01\n" +
	"\x0eVirtualMachine\x12(\n" +
	"\x04meta\x18\x01 \x01(\v2\x14.vmc.v1.ResourceMetaR\x04meta\x12\"\n" +
	"\x04spec\x18\x02 \x01(\v2\x0e.vmc.v1.VmSpecR\x04spec\x12(\n" +
	"\x06status\x18\x03 \x01(\v2\x10.vmc.v1.VmStatusR\x06status\"\xe8\x02\n" +
	"\fResourceMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0fspec_generation\x18\x03 \x01(\x03R\x0especGeneration\x12)\n" +
	"\x10resource_version\x18\x04 \x01(\x03R\x0fresourceVersion\x12)\n" +
	"\x10desired_revision\x18\x05 \x01(\x03R\x0fdesiredRevision\x12;\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12;\n" +
	"\vdelete_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deleteTime\"\xb3\x03\n" +
	"\x06VmSpec\x12\x12\n" +
	"\x04cpus\x18\x01 \x01(\rR\x04cpus\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x04R\vmemoryBytes\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12&\n" +
	"\x0froot_disk_bytes\x18\x04 \x01(\x04R\rrootDiskBytes\x12\x18\n" +
	"\anetwork\x18\x05 \x01(\tR\anetwork\x12(\n" +
	"\x05power\x18\x06 \x01(\x0e2\x12.vmc.v1.PowerStateR\x05power\x12A\n" +
	"\vconstraints\x18\a \x03(\v2\x1f.vmc.v1.VmSpec.ConstraintsEntryR\vconstraints\x122\n" +
	"\x06labels\x18\b \x03(\v2\x1a.vmc.v1.VmSpec.LabelsEntryR\x06labels\x1a>\n" +
	"\x10ConstraintsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x02\n" +
	"\bVmStatus\x12#\n" +
	"\x05phase\x18\x01 \x01(\x0e2\r.vmc.v1.PhaseR\x05phase\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x12'\n" +
	"\x0fplacement_epoch\x18\x03 \x01(\x03R\x0eplacementEpoch\x12)\n" +
	"\x10applied_revision\x18\x04 \x01(\x03R\x0fappliedRevision\x12\x17\n" +
	"\amgmt_ip\x18\x05 \x01(\tR\x06mgmtIp\x12\x1d\n" +
	"\n" +
	"last_error\x18\x06 \x01(\tR\tlastError\x121\n" +
	"\n" +
	"conditions\x18\a \x03(\v2\x11.vmc.v1.ConditionR\n" +
	"conditions\"\xd3\x01\n" +
	"\tCondition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12+\n" +
	"\x11observed_revision\x18\x05 \x01(\x03R\x10observedRevision\x12;\n" +
	"\vupdate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime*[\n" +
	"\n" +
	"PowerState\x12\x1b\n" +
	"\x17POWER_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13POWER_STATE_RUNNING\x10\x01\x12\x17\n" +
	"\x13POWER_STATE_STOPPED\x10\x02*\xbe\x01\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPHASE_PENDING\x10\x01\x12\x14\n" +
	"\x10PHASE_SCHEDULING\x10\x02\x12\x16\n" +
	"\x12PHASE_PROVISIONING\x10\x03\x12\x11\n" +
	"\rPHASE_RUNNING\x10\x04\x12\x11\n" +
	"\rPHASE_STOPPED\x10\x05\x12\x11\n" +
	"\rPHASE_UNKNOWN\x10\x06\x12\x10\n" +
	"\fPHASE_FAILED\x10\a\x12\x12\n" +
	"\x0ePHASE_DELETING\x10\bB\x88\x01\n" +
	"\n" +
	"com.vmc.v1B\aVmProtoP\x01Z8github.com/sigtunnel/vm-control-plane/proto/vmc/v1;vmcv1\xa2\x02\x03VXX\xaa\x02\x06Vmc.V1\xca\x02\x06Vmc\\V1\xe2\x02\x12Vmc\\V1\\GPBMetadata\xea\x02\aVmc::V1b\x06proto3"

var (
	file_vmc_v1_vm_proto_rawDescOnce sync.Once
	file_vmc_v1_vm_proto_rawDescData []byte
)

func file_vmc_v1_vm_proto_rawDescGZIP() []byte {
	file_vmc_v1_vm_proto_rawDescOnce.Do(func() {
		file_vmc_v1_vm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vmc_v1_vm_proto_rawDesc), len(file_vmc_v1_vm_proto_rawDesc)))
	})
	return file_vmc_v1_vm_proto_rawDescData
}

var file_vmc_v1_vm_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_vmc_v1_vm_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_vmc_v1_vm_proto_goTypes = []any{
	(PowerState)(0),               // 0: vmc.v1.PowerState
	(Phase)(0),                    // 1: vmc.v1.Phase
	(*VirtualMachine)(nil),        // 2: vmc.v1.VirtualMachine
	(*ResourceMeta)(nil),          // 3: vmc.v1.ResourceMeta
	(*VmSpec)(nil),                // 4: vmc.v1.VmSpec
	(*VmStatus)(nil),              // 5: vmc.v1.VmStatus
	(*Condition)(nil),             // 6: vmc.v1.Condition
	nil,                           // 7: vmc.v1.VmSpec.ConstraintsEntry
	nil,                           // 8: vmc.v1.VmSpec.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_vmc_v1_vm_proto_depIdxs = []int32{
	3,  // 0: vmc.v1.VirtualMachine.meta:type_name -> vmc.v1.ResourceMeta
	4,  // 1: vmc.v1.VirtualMachine.spec:type_name -> vmc.v1.VmSpec
	5,  // 2: vmc.v1.VirtualMachine.status:type_name -> vmc.v1.VmStatus
	9,  // 3: vmc.v1.ResourceMeta.create_time:type_name -> google.protobuf.Timestamp
	9,  // 4: vmc.v1.ResourceMeta.update_time:type_name -> google.protobuf.Timestamp
	9,  // 5: vmc.v1.ResourceMeta.delete_time:type_name -> google.protobuf.Timestamp
	0,  // 6: vmc.v1.VmSpec.power:type_name -> vmc.v1.PowerState
	7,  // 7: vmc.v1.VmSpec.constraints:type_name -> vmc.v1.VmSpec.ConstraintsEntry
	8,  // 8: vmc.v1.VmSpec.labels:type_name -> vmc.v1.VmSpec.LabelsEntry
	1,  // 9: vmc.v1.VmStatus.phase:type_name -> vmc.v1.Phase
	6,  // 10: vmc.v1.VmStatus.conditions:type_name -> vmc.v1.Condition
	9,  // 11: vmc.v1.Condition.update_time:type_name -> google.protobuf.Timestamp
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_vmc_v1_vm_proto_init() }
func file_vmc_v1_vm_proto_init() {
	if File_vmc_v1_vm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vmc_v1_vm_proto_rawDesc), len(file_vmc_v1_vm_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vmc_v1_vm_proto_goTypes,
		DependencyIndexes: file_vmc_v1_vm_proto_depIdxs,
		EnumInfos:         file_vmc_v1_vm_proto_enumTypes,
		MessageInfos:      file_vmc_v1_vm_proto_msgTypes,
	}.Build()
	File_vmc_v1_vm_proto = out.File
	file_vmc_v1_vm_proto_goTypes = nil
	file_vmc_v1_vm_proto_depIdxs = nil
}
