// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: vmc/v1/vm_service.proto

package vmcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VMService_CreateVm_FullMethodName      = "/vmc.v1.VMService/CreateVm"
	VMService_UpdateVmPower_FullMethodName = "/vmc.v1.VMService/UpdateVmPower"
	VMService_DeleteVm_FullMethodName      = "/vmc.v1.VMService/DeleteVm"
	VMService_GetVm_FullMethodName         = "/vmc.v1.VMService/GetVm"
	VMService_ListVms_FullMethodName       = "/vmc.v1.VMService/ListVms"
)

// VMServiceClient is the client API for VMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VMService is the public API. Every mutating RPC carries an idempotency
// key minted by the CLIENT before its first attempt: a timeout-and-retry
// replays the same key, and the server's idempotency envelope (keyed on it,
// storing method + canonical request hash) is the serialization point —
// same key + same request returns the original operation; same key +
// different request is FAILED_PRECONDITION (plan D3).
type VMServiceClient interface {
	CreateVm(ctx context.Context, in *CreateVmRequest, opts ...grpc.CallOption) (*Operation, error)
	// UpdateVmPower is the ONLY mutable-spec verb in v0.1 (plan D3): it bumps
	// spec_generation and desired_revision under a resource_version
	// precondition; everything else about a VM is immutable after create.
	UpdateVmPower(ctx context.Context, in *UpdateVmPowerRequest, opts ...grpc.CallOption) (*Operation, error)
	DeleteVm(ctx context.Context, in *DeleteVmRequest, opts ...grpc.CallOption) (*Operation, error)
	GetVm(ctx context.Context, in *GetVmRequest, opts ...grpc.CallOption) (*VirtualMachine, error)
	ListVms(ctx context.Context, in *ListVmsRequest, opts ...grpc.CallOption) (*ListVmsResponse, error)
}

type vMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVMServiceClient(cc grpc.ClientConnInterface) VMServiceClient {
	return &vMServiceClient{cc}
}

func (c *vMServiceClient) CreateVm(ctx context.Context, in *CreateVmRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, VMService_CreateVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) UpdateVmPower(ctx context.Context, in *UpdateVmPowerRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, VMService_UpdateVmPower_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) DeleteVm(ctx context.Context, in *DeleteVmRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, VMService_DeleteVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) GetVm(ctx context.Context, in *GetVmRequest, opts ...grpc.CallOption) (*VirtualMachine, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VirtualMachine)
	err := c.cc.Invoke(ctx, VMService_GetVm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) ListVms(ctx context.Context, in *ListVmsRequest, opts ...grpc.CallOption) (*ListVmsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVmsResponse)
	err := c.cc.Invoke(ctx, VMService_ListVms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VMServiceServer is the server API for VMService service.
// All implementations must embed UnimplementedVMServiceServer
// for forward compatibility.
//
// VMService is the public API. Every mutating RPC carries an idempotency
// key minted by the CLIENT before its first attempt: a timeout-and-retry
// replays the same key, and the server's idempotency envelope (keyed on it,
// storing method + canonical request hash) is the serialization point —
// same key + same request returns the original operation; same key +
// different request is FAILED_PRECONDITION (plan D3).
type VMServiceServer interface {
	CreateVm(context.Context, *CreateVmRequest) (*Operation, error)
	// UpdateVmPower is the ONLY mutable-spec verb in v0.1 (plan D3): it bumps
	// spec_generation and desired_revision under a resource_version
	// precondition; everything else about a VM is immutable after create.
	UpdateVmPower(context.Context, *UpdateVmPowerRequest) (*Operation, error)
	DeleteVm(context.Context, *DeleteVmRequest) (*Operation, error)
	GetVm(context.Context, *GetVmRequest) (*VirtualMachine, error)
	ListVms(context.Context, *ListVmsRequest) (*ListVmsResponse, error)
	mustEmbedUnimplementedVMServiceServer()
}

// UnimplementedVMServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVMServiceServer struct{}

func (UnimplementedVMServiceServer) CreateVm(context.Context, *CreateVmRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVm not implemented")
}
func (UnimplementedVMServiceServer) UpdateVmPower(context.Context, *UpdateVmPowerRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVmPower not implemented")
}
func (UnimplementedVMServiceServer) DeleteVm(context.Context, *DeleteVmRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVm not implemented")
}
func (UnimplementedVMServiceServer) GetVm(context.Context, *GetVmRequest) (*VirtualMachine, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVm not implemented")
}
func (UnimplementedVMServiceServer) ListVms(context.Context, *ListVmsRequest) (*ListVmsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVms not implemented")
}
func (UnimplementedVMServiceServer) mustEmbedUnimplementedVMServiceServer() {}
func (UnimplementedVMServiceServer) testEmbeddedByValue()                   {}

// UnsafeVMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VMServiceServer will
// result in compilation errors.
type UnsafeVMServiceServer interface {
	mustEmbedUnimplementedVMServiceServer()
}

func RegisterVMServiceServer(s grpc.ServiceRegistrar, srv VMServiceServer) {
	// If the following call panics, it indicates UnimplementedVMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VMService_ServiceDesc, srv)
}

func _VMService_CreateVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).CreateVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_CreateVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).CreateVm(ctx, req.(*CreateVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_UpdateVmPower_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVmPowerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).UpdateVmPower(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_UpdateVmPower_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).UpdateVmPower(ctx, req.(*UpdateVmPowerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_DeleteVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).DeleteVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_DeleteVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).DeleteVm(ctx, req.(*DeleteVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_GetVm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).GetVm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_GetVm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).GetVm(ctx, req.(*GetVmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_ListVms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).ListVms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_ListVms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).ListVms(ctx, req.(*ListVmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VMService_ServiceDesc is the grpc.ServiceDesc for VMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vmc.v1.VMService",
	HandlerType: (*VMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVm",
			Handler:    _VMService_CreateVm_Handler,
		},
		{
			MethodName: "UpdateVmPower",
			Handler:    _VMService_UpdateVmPower_Handler,
		},
		{
			MethodName: "DeleteVm",
			Handler:    _VMService_DeleteVm_Handler,
		},
		{
			MethodName: "GetVm",
			Handler:    _VMService_GetVm_Handler,
		},
		{
			MethodName: "ListVms",
			Handler:    _VMService_ListVms_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vmc/v1/vm_service.proto",
}
