// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: vmc/v1/vm_service.proto

package vmcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateVmPowerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Power          PowerState             `protobuf:"varint,3,opt,name=power,proto3,enum=vmc.v1.PowerState" json:"power,omitempty"`
	// Optional optimistic-concurrency precondition: when non-zero, the update
	// applies only if the row's resource_version still matches.
	ExpectedResourceVersion int64 `protobuf:"varint,4,opt,name=expected_resource_version,json=expectedResourceVersion,proto3" json:"expected_resource_version,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UpdateVmPowerRequest) Reset() {
	*x = UpdateVmPowerRequest{}
	mi := &file_vmc_v1_vm_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVmPowerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVmPowerRequest) ProtoMessage() {}

func (x *UpdateVmPowerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_vm_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVmPowerRequest.ProtoReflect.Descriptor instead.
func (*UpdateVmPowerRequest) Descriptor() ([]byte, []int) {
	return file_vmc_v1_vm_service_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateVmPowerRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *UpdateVmPowerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateVmPowerRequest) GetPower() PowerState {
	if x != nil {
		return x.Power
	}
	return PowerState_POWER_STATE_UNSPECIFIED
}

func (x *UpdateVmPowerRequest) GetExpectedResourceVersion() int64 {
	if x != nil {
		return x.ExpectedResourceVersion
	}
	return 0
}

type CreateVmRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client-minted UUID; the idempotency envelope key.
	IdempotencyKey string  `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Name           string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Spec           *VmSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateVmRequest) Reset() {
	*x = CreateVmRequest{}
	mi := &file_vmc_v1_vm_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmRequest) ProtoMessage() {}

func (x *CreateVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_vm_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmRequest.ProtoReflect.Descriptor instead.
func (*CreateVmRequest) Descriptor() ([]byte, []int) {
	return file_vmc_v1_vm_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVmRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateVmRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVmRequest) GetSpec() *VmSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type DeleteVmRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteVmRequest) Reset() {
	*x = DeleteVmRequest{}
	mi := &file_vmc_v1_vm_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVmRequest) ProtoMessage() {}

func (x *DeleteVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_vm_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVmRequest.ProtoReflect.Descriptor instead.
func (*DeleteVmRequest) Descriptor() ([]byte, []int) {
	return file_vmc_v1_vm_service_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteVmRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *DeleteVmRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmRequest) Reset() {
	*x = GetVmRequest{}
	mi := &file_vmc_v1_vm_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmRequest) ProtoMessage() {}

func (x *GetVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_vm_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmRequest.ProtoReflect.Descriptor instead.
func (*GetVmRequest) Descriptor() ([]byte, []int) {
	return file_vmc_v1_vm_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetVmRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListVmsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page size 0 means server default.
	PageSize      int32  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVmsRequest) Reset() {
	*x = ListVmsRequest{}
	mi := &file_vmc_v1_vm_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVmsRequest) ProtoMessage() {}

func (x *ListVmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_vm_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVmsRequest.ProtoReflect.Descriptor instead.
func (*ListVmsRequest) Descriptor() ([]byte, []int) {
	return file_vmc_v1_vm_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListVmsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListVmsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListVmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*VirtualMachine      `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVmsResponse) Reset() {
	*x = ListVmsResponse{}
	mi := &file_vmc_v1_vm_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVmsResponse) ProtoMessage() {}

func (x *ListVmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vmc_v1_vm_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVmsResponse.ProtoReflect.Descriptor instead.
func (*ListVmsResponse) Descriptor() ([]byte, []int) {
	return file_vmc_v1_vm_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListVmsResponse) GetVms() []*VirtualMachine {
	if x != nil {
		return x.Vms
	}
	return nil
}

func (x *ListVmsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_vmc_v1_vm_service_proto protoreflect.FileDescriptor

const file_vmc_v1_vm_service_proto_rawDesc = "" +
	"\n" +
	"\x17vmc/v1/vm_service.proto\x12\x06vmc.v1\x1a\x16vmc/v1/operation.proto\x1a\x0fvmc/v1/vm.proto\"\xb9\x01\n" +
	"\x14UpdateVmPowerRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x05power\x18\x03 \x01(\x0e2\x12.vmc.v1.PowerStateR\x05power\x12:\n" +
	"\x19expected_resource_version\x18\x04 \x01(\x03R\x17expectedResourceVersion\"r\n" +
	"\x0fCreateVmRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\x04spec\x18\x03 \x01(\v2\x0e.vmc.v1.VmSpecR\x04spec\"N\n" +
	"\x0fDeleteVmRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\"\n" +
	"\fGetVmRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"L\n" +
	"\x0eListVmsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"c\n" +
	"\x0fListVmsResponse\x12(\n" +
	"\x03vms\x18\x01 \x03(\v2\x16.vmc.v1.VirtualMachineR\x03vms\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xb0\x02\n" +
	"\tVMService\x126\n" +
	"\bCreateVm\x12\x17.vmc.v1.CreateVmRequest\x1a\x11.vmc.v1.Operation\x12@\n" +
	"\rUpdateVmPower\x12\x1c.vmc.v1.UpdateVmPowerRequest\x1a\x11.vmc.v1.Operation\x126\n" +
	"\bDeleteVm\x12\x17.vmc.v1.DeleteVmRequest\x1a\x11.vmc.v1.Operation\x125\n" +
	"\x05GetVm\x12\x14.vmc.v1.GetVmRequest\x1a\x16.vmc.v1.VirtualMachine\x12:\n" +
	"\aListVms\x12\x16.vmc.v1.ListVmsRequest\x1a\x17.vmc.v1.ListVmsResponseB\x8f\x01\n" +
	"\n" +
	"com.vmc.v1B\x0eVmServiceProtoP\x01Z8github.com/sigtunnel/vm-control-plane/proto/vmc/v1;vmcv1\xa2\x02\x03VXX\xaa\x02\x06Vmc.V1\xca\x02\x06Vmc\\V1\xe2\x02\x12Vmc\\V1\\GPBMetadata\xea\x02\aVmc::V1b\x06proto3"

var (
	file_vmc_v1_vm_service_proto_rawDescOnce sync.Once
	file_vmc_v1_vm_service_proto_rawDescData []byte
)

func file_vmc_v1_vm_service_proto_rawDescGZIP() []byte {
	file_vmc_v1_vm_service_proto_rawDescOnce.Do(func() {
		file_vmc_v1_vm_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vmc_v1_vm_service_proto_rawDesc), len(file_vmc_v1_vm_service_proto_rawDesc)))
	})
	return file_vmc_v1_vm_service_proto_rawDescData
}

var file_vmc_v1_vm_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_vmc_v1_vm_service_proto_goTypes = []any{
	(*UpdateVmPowerRequest)(nil), // 0: vmc.v1.UpdateVmPowerRequest
	(*CreateVmRequest)(nil),      // 1: vmc.v1.CreateVmRequest
	(*DeleteVmRequest)(nil),      // 2: vmc.v1.DeleteVmRequest
	(*GetVmRequest)(nil),         // 3: vmc.v1.GetVmRequest
	(*ListVmsRequest)(nil),       // 4: vmc.v1.ListVmsRequest
	(*ListVmsResponse)(nil),      // 5: vmc.v1.ListVmsResponse
	(PowerState)(0),              // 6: vmc.v1.PowerState
	(*VmSpec)(nil),               // 7: vmc.v1.VmSpec
	(*VirtualMachine)(nil),       // 8: vmc.v1.VirtualMachine
	(*Operation)(nil),            // 9: vmc.v1.Operation
}
var file_vmc_v1_vm_service_proto_depIdxs = []int32{
	6, // 0: vmc.v1.UpdateVmPowerRequest.power:type_name -> vmc.v1.PowerState
	7, // 1: vmc.v1.CreateVmRequest.spec:type_name -> vmc.v1.VmSpec
	8, // 2: vmc.v1.ListVmsResponse.vms:type_name -> vmc.v1.VirtualMachine
	1, // 3: vmc.v1.VMService.CreateVm:input_type -> vmc.v1.CreateVmRequest
	0, // 4: vmc.v1.VMService.UpdateVmPower:input_type -> vmc.v1.UpdateVmPowerRequest
	2, // 5: vmc.v1.VMService.DeleteVm:input_type -> vmc.v1.DeleteVmRequest
	3, // 6: vmc.v1.VMService.GetVm:input_type -> vmc.v1.GetVmRequest
	4, // 7: vmc.v1.VMService.ListVms:input_type -> vmc.v1.ListVmsRequest
	9, // 8: vmc.v1.VMService.CreateVm:output_type -> vmc.v1.Operation
	9, // 9: vmc.v1.VMService.UpdateVmPower:output_type -> vmc.v1.Operation
	9, // 10: vmc.v1.VMService.DeleteVm:output_type -> vmc.v1.Operation
	8, // 11: vmc.v1.VMService.GetVm:output_type -> vmc.v1.VirtualMachine
	5, // 12: vmc.v1.VMService.ListVms:output_type -> vmc.v1.ListVmsResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_vmc_v1_vm_service_proto_init() }
func file_vmc_v1_vm_service_proto_init() {
	if File_vmc_v1_vm_service_proto != nil {
		return
	}
	file_vmc_v1_operation_proto_init()
	file_vmc_v1_vm_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vmc_v1_vm_service_proto_rawDesc), len(file_vmc_v1_vm_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vmc_v1_vm_service_proto_goTypes,
		DependencyIndexes: file_vmc_v1_vm_service_proto_depIdxs,
		MessageInfos:      file_vmc_v1_vm_service_proto_msgTypes,
	}.Build()
	File_vmc_v1_vm_service_proto = out.File
	file_vmc_v1_vm_service_proto_goTypes = nil
	file_vmc_v1_vm_service_proto_depIdxs = nil
}
